Attempt to solve job id size
ERROR    airflow.task:taskinstance.py:3336 Task failed with exception
Traceback (most recent call last):
  File "/home/runner/.local/share/hatch/env/virtual/astro-provider-anyscale/UDnurkOL/tests.py3.11-2.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/astro-provider-anyscale/UDnurkOL/tests.py3.11-2.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/astro-provider-anyscale/UDnurkOL/tests.py3.11-2.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/astro-provider-anyscale/UDnurkOL/tests.py3.11-2.11/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/astro-provider-anyscale/astro-provider-anyscale/anyscale_provider/operators/anyscale.py", line 383, in execute
    self.service_id = self.hook.deploy_service(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/astro-provider-anyscale/astro-provider-anyscale/anyscale_provider/hooks/anyscale.py", line 118, in deploy_service
    service_id: str = self.client.service.deploy(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/astro-provider-anyscale/UDnurkOL/tests.py3.11-2.11/lib/python3.11/site-packages/anyscale/service/__init__.py", line 87, in deploy
    return self._private_sdk.deploy(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/astro-provider-anyscale/UDnurkOL/tests.py3.11-2.11/lib/python3.11/site-packages/anyscale/service/_private/service_sdk.py", line 820, in deploy
    service = self.client.rollout_service(model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/share/hatch/env/virtual/astro-provider-anyscale/UDnurkOL/tests.py3.11-2.11/lib/python3.11/site-packages/anyscale/_private/anyscale_client/anyscale_client.py", line 176, in wrapper
    raise ValueError(msg) from None
ValueError: Unable to create Service with name AstroService-CICD-test-refs-heads-airflow3-support-3-11-2-11. Service names must be no longer than 57 characters and can only contain alphanumeric characters, dashes, and underscores. Please recreate the service with a valid name.

https://github.com/astronomer/astro-provider-anyscale/actions/runs/19546379457/job/55966148810
(cherry picked from commit a6af92cf028612efb48664d93e6611e191ecf708)